name: DevSecOps Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build:
    name: Build and Push DVWA Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for pushing to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated from v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --tag ghcr.io/${{ github.repository_owner }}/dvwa:latest \
            --tag ghcr.io/${{ github.repository_owner }}/dvwa:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/dvwa:latest
          docker push ghcr.io/${{ github.repository_owner }}/dvwa:${{ github.sha }}

  semgrep_scan:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated from v3

      - name: Perform Semgrep Analysis
        run: semgrep scan -q --sarif --config auto . > semgrep-results.sarif

      - name: Save SARIF results as artifact
        uses: actions/upload-artifact@v4  # Fixed: Updated from v3 to v4
        with:
          name: semgrep-scan-results
          path: semgrep-results.sarif

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
        if: always()

  gitleaks:
    name: Secrets Scan - Gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Needed for code scanning
      security-events: write  # Needed to upload results
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full git history scanning

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml  # Optional custom config
          format: sarif
          output: gitleaks.sarif
          no-git: false  # Ensure git scanning is enabled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify report exists
        run: |
          if [ -f "gitleaks.sarif" ]; then
            echo "Report generated successfully"
            cat gitleaks.sarif | jq empty  # Validate JSON
          else
            echo "No report generated - creating empty file"
            echo '{"version": "2.1.0", "$schema": "https://json.schemastore.org/sarif-2.1.0.json", "runs": []}' > gitleaks.sarif
          fi
          
      - name: Upload Gitleaks report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks


  dependency-check:
    name: SCA - Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'DVWA'
          format: 'ALL'
          out: 'reports'
          
      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/
        if: always()
    

  dast:
    name: DAST - OWASP ZAP Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      packages: read

    services:
      docker:
        image: docker:dind
        options: --privileged
    container:
      image: ubuntu:22.04  # More specific version

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker and dependencies
        run: |
          apt-get update
          apt-get install -y docker.io curl jq

      - name: Verify Docker
        run: |
          docker version
          docker info

      - name: Deploy DVWA with healthcheck
        run: |
          # Start DVWA with explicit environment variables
          docker run -d \
            --name dvwa \
            -p 3000:80 \
            -e PHPIDS_ENABLED=false \
            -e DVWA_SECURITY=low \
            --health-cmd="curl -f http://localhost || exit 1" \
            --health-interval=5s \
            --health-retries=10 \
            vulnerables/web-dvwa
        
          # Wait for container to be healthy
          echo "Waiting for DVWA to initialize..."
          timeout 180 bash -c 'while [[ $(docker inspect -f "{{.State.Health.Status}}" dvwa) != "healthy" ]]; do
            sleep 5
            echo "Still waiting for DVWA to be ready..."
          done'
        
          # Additional verification
          echo "DVWA container status:"
          docker ps -a
          docker logs dvwa --tail 50
        
          echo "Testing DVWA access..."
          curl -v http://localhost:3000

      - name: Run OWASP ZAP Scan
        run: |
          # Pull ZAP image
          docker pull owasp/zap2docker-stable
        
          # Run scan with increased timeout
          docker run --network host -i owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:3000 \
            -r scan_report.html \
            -m 5
        
          # Store report
          mkdir -p zap-reports
          docker cp $(docker ps -alq):/zap/scan_report.html zap-reports/
        
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap-reports/scan_report.html
